# Generated by Django 5.0.2 on 2024-05-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade_comprado', models.IntegerField()),
                ('quantidade_vendido', models.IntegerField()),
                ('fabricante', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=255)),
                ('subgrupo', models.CharField(max_length=255)),
            ],
        ),
    ]
