# Generated by Django 5.0.2 on 2024-05-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0004_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_vendido',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_app.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastro_app.venda')),
            ],
        ),
    ]
